### ISSUE TITLE
Can't rebuild because of a broken plugin?

### ISSUE THREAD

**Issue by Alyzmal** [NixNeovim/NixNeovimPlugins#69]
Whenever I try to rebuild after updating my flake lock file to the latest commit, it errors out and tells me that "gitlinker-nvim" is defined twice in pkgs/vim_plugins.nix. Is this a plugin issue and will it be resolved soon?

**Comment by jooooscha** [comment]
It should be fixed now. Please report if that is not the case.

**Comment by mirkolenz** [comment]
It works for me  now, thanks for acting this fast! Just in case something like this happens again in the future: Is there a way to temporarily disable certain plugins that one does not use (e.g., via an override mechanism)?

**Comment by jooooscha** [comment]
I am not sure if this can be fixed in nix. I think a better approach would be to prevent this from happening in the first case.

Maybe the update action should only create a PR instead of committing 🤔

If #54 will ever get finished, we could also implement a check, such that a broken packages list will be detected at creation time

**Comment by mirkolenz** [comment]
Thanks for the feedback, the PR looks promising! Maybe it could be useful to set up tests using a language server like `nil` or `nixd` as an interim solution? While they will not be able to check for correct compilation/rebuilding, they should at least identify collisions like this one.

**Comment by Alyzmal** [comment]
Everything's fixed! Thanks! I hope the PR is productive so we can circumvent these issues in the future!

**Comment by jooooscha** [comment]
> ... set up tests using a language server like nil or nixd as an interim solution

I have a GitHub Action that opens an issue for duplicated plugins. However, I could not identify the problem, because of a bug in that Action. Only when you opened the issue, I took the time to look into that.

> I hope the PR is productive

It was started by @MoritzBoehme and I did not have the time yet to look at it in detail to determine its state.
I am afraid I will not have that time either in the near future, so If you have the time and knowledge, please go ahead :P

Until that's finished, we will need to stick to manually fixing these kinds of bugs, unfortunately 🤷
